[package]
name="js"
authors=["David J. Pearce"]
version="0.1.3"

[build]
platforms=["whiley","js"]

[build.whiley]
source="src/whiley"
verify=false

[build.js]
includes=["src/js/**/*.js"]

[dependencies]
std="0.2.16"
